1) SELECT*FROM Jaegers;
2) SELECT modelname FROM Jaegers WHERE status!= 'Destroyed';
3) SELECT modelname FROM Jaegers WHERE mark = 'mark-6' OR mark = 'mark-1';
4) SELECT * FROM Jaegers ORDER BY mark DESC;
5) SELECT modelname FROM Jaegers WHERE launch = (SELECT MIN(launch) FROM Jaegers);
6) SELECT modelname FROM Jaegers WHERE kaijukill = (SELECT MIN(kaijukill)  FROM Jaegers);
   SELECT modelname FROM Jaegers WHERE kaijukill = (SELECT MAX(kaijukill)  FROM Jaegers);
7) SELECT AVG(weight) FROM Jaegers;
8) SELECT kaijukill + 1 FROM Jaegers WHERE status != 'Destroyed';
9) DELETE FROM JAegers WHERE staus = 'Destroyed';