SELECT * FROM Jaegers;
SELECT modelName FROM Jaegers WHERE status != 'Destroyed';
SELECT modelName FROM Jaegers WHERE mark = 'mark-6' OR mark = 'mark-1';
SELECT * FROM Jaegers ORDER BY mark DESC;
SELECT modelName FROM Jaegers WHERE launch = (SELECT MIN(launch) FROM Jaegers);
SELECT modelName FROM Jaegers WHERE kaijukill = (SELECT MIN(kaijukill)  FROM Jaegers);
SELECT modelName FROM Jaegers WHERE kaijukill = (SELECT MAX(kaijukill)  FROM Jaegers);
SELECT AVG(weight) FROM Jaegers;
SELECT kaijukill + 1 FROM Jaegers WHERE status != 'Destroyed';
DELETE FROM Jaegers WHERE staus = 'Destroyed';